// title — artist (transcribed from screenshots; #13-14, #27-30 were cut off)
export const SONGS = [
  { title: 'Is This Love', artist: 'Bob Marley & The Wailers' },
  { title: 'Bohemian Rhapsody', artist: 'Queen' },
  { title: 'Hey Jude', artist: 'The Beatles' },
  { title: 'Too Much Heaven', artist: 'Bee Gees' },
  { title: 'Fairytale', artist: 'Alexander Rybak' },
  { title: 'Ordinary World', artist: 'Duran Duran' },
  { title: 'Diamonds', artist: 'Rihanna' },
  { title: 'My Way', artist: 'Frank Sinatra' },
  { title: 'Udeekan Vich', artist: 'Armaan Bedil' },
  { title: 'Ehsaas', artist: 'Faheem Abdullah' },
  { title: 'Sadi Sun', artist: 'Harsh Nussi' },
  { title: 'Dil Dardeh', artist: 'Sukha The PropheC' },
  { title: 'Udaarian', artist: 'Satinder Sartaaj' },
  { title: 'Midnight Call', artist: 'Harkirat Sangha Starboy X' },
  { title: 'Piche Tere', artist: 'Kunwarr Dishant' },
  { title: 'Judge', artist: 'Amrinder Gill Dr Zeus' },
  { title: 'Good Luck Charm', artist: 'K S Makhan' },
  { title: 'Zamaana Lage', artist: 'Pritam Arijit Singh' },
  { title: 'Kehne Lagaa', artist: 'Rushil Aswal' },
  { title: 'happier', artist: 'Olivia Rodrigo' },
  { title: 'WILDFLOWER', artist: 'Billie Eilish' },
  { title: 'Sab Tera', artist: 'Armaan Malik' },
  { title: 'Mann Mera', artist: 'Gajendra Verma' },
  { title: 'Distance Love', artist: 'Zehr Vibe' },
  { title: 'Barsaat', artist: 'Banjaare Roni' },
  { title: 'Eye Contact', artist: 'Harsh Nussi Deep Klair' },
  { title: 'She Ain\'t Easy', artist: 'Navaan Sandhu' },
  { title: 'ASTARR', artist: 'Prem Dhillon' },
  { title: 'Young G.O.A.T', artist: 'Cheema Y Gur Sidhu' },
  { title: 'Aas Dil Da Ki Banuga', artist: 'Navjeet' },
  { title: 'Deewana', artist: 'Akhil' },
  { title: 'WANG', artist: 'Sukha Manni Sandhu' },
  { title: 'Your Thoughts', artist: 'Nav Singh' },
  { title: 'GALL MUKKDI', artist: 'BK Arsh Heer' },
  { title: 'Brabus', artist: 'Parmish Verma' },
  { title: 'Tich Button', artist: 'Kulwinder Billa' },
  { title: 'Geet De Wargi', artist: 'Tarsem Jassar' },
  { title: 'Taskari', artist: 'HAQ Syphr' },
  { title: 'Fade Low', artist: 'Yaad JAY D' },
  { title: 'No Worries', artist: 'DesiFrenzy Uday Shergill' },
  { title: 'NAZAR', artist: 'Armaan Gill' },
  { title: 'I Really Do', artist: 'Karan Aujla Ikky' },
  { title: 'Fell For You', artist: 'Shubh' },
  { title: 'Sun Saawariya', artist: 'Accha Insaan' },
];
